name: Continuous Integration

# TODO Restrict deployment to master branch
on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          # ignore: "F401"
          # exclude: "src/ignoreme.py"
          max-line-length: "120"
          path: "src"
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 0xjem/discord-bots:latest
          cache-from: type=gha
          cache-to: type=gha
  deploy:
    name: Deploy Digital Ocean App
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Install doctl
        run: snap install doctl
      - name: Create app
        run: doctl apps create --upsert --spec app-spec.yml
      - name: Deploy app
        run: doctl apps create-deployment discord-bots
