name: Continuous Integration

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          # ignore: "F401"
          # exclude: "src/ignoreme.py"
          max-line-length: "120"
          path: "src"
  build-docker:
    runs-on: ubuntu-latest
    name: Build Docker image
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 0xjem/discord-bots:latest
          cache-from: type=gha
          cache-to: type=gha
  deploy-bct:
    runs-on: ubuntu-latest
    container: 
      image: 0xjem/discord-bots:latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Test
        run: echo Yay
# Use docker image
# Restrict deployment to master branch
# Deploy to DOAP
