name: Continuous Integration

# TODO Restrict deployment to master branch
on:
  push:
    branches:
      - docker

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: "120"
          path: "src"
  build-docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.digitalocean.com/${{ secrets.DIGITALOCEAN_CONTAINER_REPO }}/discord-bots:latest
          cache-from: type=gha
          cache-to: type=gha
          target: prod
  deploy:
    name: Deploy Digital Ocean App
    runs-on: ubuntu-latest
    needs: build-docker
    env:
      POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
      WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
      DISCORD_BOT_TOKEN_REBASE: ${{ secrets.DISCORD_BOT_TOKEN_REBASE }}
      DISCORD_BOT_WEBHOOK_REBASE: ${{ secrets.DISCORD_BOT_WEBHOOK_REBASE }}
      DISCORD_BOT_TOKEN_KLIMA_PRICE: ${{ secrets.DISCORD_BOT_TOKEN_KLIMA_PRICE }}
      DISCORD_BOT_TOKEN_BCT_PRICE: ${{ secrets.DISCORD_BOT_TOKEN_BCT_PRICE }}
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      # TODO update doctl to use 2fcbadcb46efd8dca0d93fbef2a3a8394f5981ba with the error code fix
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Install envplate
        run: make install_envplate
      - name: Check variables
        uses: svrooij/secret-gate-action@v1
        with:
          inputsToCheck: "POLYGONSCAN_API_KEY,WEB3_INFURA_PROJECT_ID,DISCORD_BOT_TOKEN_REBASE,DISCORD_BOT_WEBHOOK_REBASE,DISCORD_BOT_TOKEN_KLIMA_PRICE,DISCORD_BOT_TOKEN_BCT_PRICE"
          failOnMissing: "true"
      - name: Replace variables
        run: make replace_variables
      - name: Upsert app
        run: doctl apps update ${{ secrets.DIGITALOCEAN_APP_ID }} --spec app-spec.yml --wait --verbose
